import type { DaoDetail } from './elioStore';

export const daoArray: DaoDetail[] = [
  {
    daoId: '1',
    daoName: 'Example DAO 1',
    daoOwnerAddress: '0x1234567890',
    daoCreatorAddress: '0x0987654321',
    setupComplete: true,
    daoAssetId: null,
    metadataUrl: null,
    metadataHash: null,
    descriptionShort: 'Short description of Example DAO 1',
    descriptionLong: 'Longer description of Example DAO 1',
    email: 'exampledao1@example.com',
    images: {
      contentType: null,
      small: null,
      medium: null,
      large: null,
    },
  },
  {
    daoId: '2',
    daoName: 'Example DAO 2',
    daoOwnerAddress: '0x2345678901',
    daoCreatorAddress: '0x9876543210',
    setupComplete: false,
    daoAssetId: 123,
    metadataUrl: 'https://example.com/metadata',
    metadataHash: 'abcdefg',
    descriptionShort: 'Short description of Example DAO 2',
    descriptionLong: 'Longer description of Example DAO 2',
    email: null,
    images: {
      contentType: 'image/png',
      small: 'https://example.com/image-small.png',
      medium: 'https://example.com/image-medium.png',
      large: 'https://example.com/image-large.png',
    },
  },
  {
    daoId: '3',
    daoName: 'Example DAO 3',
    daoOwnerAddress: '0x3456789012',
    daoCreatorAddress: '0x8765432109',
    setupComplete: true,
    daoAssetId: null,
    metadataUrl: null,
    metadataHash: null,
    descriptionShort: 'Short description of Example DAO 3',
    descriptionLong: 'Longer description of Example DAO 3',
    email: 'exampledao3@example.com',
    images: {
      contentType: 'image/jpeg',
      small: 'https://example.com/image-small.jpg',
      medium: 'https://example.com/image-medium.jpg',
      large: 'https://example.com/image-large.jpg',
    },
  },
];
